##database configuration--->
#
#spring :
#  datasource:
#   url: jdbc:mysql://localhost:3306/hotelbookingDB
#   username: sauravS
#   password: saurav@simmi
#   driverClassName: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      format_sql: true
#  servlet:
#    multipart:
#      max-file-size: 5MB
#      max-request-size: 5MB
#      file-size-threshold: 2KB
#
#      security:
#          jwt:
#            secret-key: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D
#            expire-length: 3600000